// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytomchbcdfocierzxbbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0b21jaGJjZGZvY2llcnp4YmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzQ4MzUsImV4cCI6MjA3MTc1MDgzNX0.c856JIjJ8DnyVHVbV_rvfj1pPV4mEAu1pD1yviiwkNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});